channels:
  - conda-forge
  - bioconda
  
dependencies:
  - python=3.7
  - samtools=1.22.1
  - bc=1.07.1
  - pip
  - pip:
      - pysam>=0.22.0

  # R packages
  - r-base=4.3.*
  - r-data.table
  - r-argparse