channels:
  - conda-forge
  - bioconda

dependencies:
  - bioconda::alevin-fry=0.11.2
  - bioconda::piscem=0.12.2
  - bioconda::salmon=1.10.3
  - bioconda::simpleaf=0.19.4
  - conda-forge::pip

  - pip:
      - seqspec
