# MultiQC Configuration File

# General settings
dirs: true
verbose: true
force: true

report_header_info:
  - Contact E-mail: "bca@biodiversitycellatlas.org"
  - Application Type: "BCA Pre-Processing Pipeline"
  - Application Version: "1.0.0"

# Custom settings
custom_logo: "nf-core-bca_preprocessing_logo_light.png"
custom_logo_title: "Biodiversity Cell Atlas"
